### ISSUE TITLE
G780F kernel source was copied over to G780G

### ISSUE THREAD

**Issue by pascua28** [Linux4/samsung_kernel#1]
As the title says, in the latest commit, G780F was copied over to G780G source. For example, G780G is in Linux 4.19.113 but the latest commit changed it to 4.19.87 which is what the G780F source uses. Also, a lot of exynos-specific stuffs were added that shouldn't have been here. Most of CAF's changes to the common kernel code were also overwritten with the G780F's ones.

**Comment by Linux4** [comment]
I just downloaded that source directly from opensource.samsung.com, and it seems it's their mistake, so nothing wrong with the bot. You might want to request the correct one from samsung.

**Comment by pascua28** [comment]
Ok, so it's Samsung's fault. But why is the branch still not updated? It still has that erroneous commit

**Comment by Linux4** [comment]
All the source in this repo is automatically committed by the bot from github.com/Linux4/SamsungFirmwareBot
It's a mirror of the kernels on opensource.samsung.com, I won't manually change things here, it'll be fixed as soon as samsung uploads proper sources.
